import '../../models/cheatsheet.dart';

final Cheatsheet electricityCheatsheet = Cheatsheet(
  category: 'Electricity',
  summary: 'Basic principles of electricity, circuit designs, component behaviors, and fundamental equations.',
  sections: [
    CheatsheetSection(
      title: 'Ohm\'s Law & Electrical Power',
      content: 'Ohm\'s Law describes the mathematical relationship between the three core electrical properties of a circuit.',
      bulletPoints: [
        'Voltage (V): Electric potential difference, measured in Volts (V). The "force" pushing current.',
        'Current (I): Rate of flow of electric charge, measured in Amperes (A) or Amps.',
        'Resistance (R): The opposition to the flow of electric current, measured in Ohms (Ω).',
        'Ohm\'s Equation: V = I * R (Voltage equals Current times Resistance).',
        'Electrical Power (P): Rate of electrical energy consumption/generation, measured in Watts (W). P = V * I.',
      ],
      codeSnippet: 'Ohm\'s Triangle:\n      V\n     --- \n    I | R\n\n- Solve for V: V = I * R\n- Solve for I: I = V / R\n- Solve for R: R = V / I',
    ),
    CheatsheetSection(
      title: 'AC vs. DC Current',
      content: 'Electric current flows in two primary configurations, depending on how voltage is generated.',
      bulletPoints: [
        'DC (Direct Current): Charge flows strictly in one direction. Generated by batteries, solar cells, and USB chargers.',
        'AC (Alternating Current): Charge direction reverses periodically. Easier to step up to high voltages for long-distance grid transmission with minimal loss.',
        'Rectifier: An electrical circuit configuration (often using diodes) that converts AC to DC.',
      ],
      codeSnippet: 'DC: Constant voltage over time (flat line)\nAC: Sinusoidal voltage over time (sine wave)',
    ),
    CheatsheetSection(
      title: 'Series vs. Parallel Circuits',
      content: 'Electrical components can be wired together in series or parallel, directly impacting voltages and currents.',
      bulletPoints: [
        'Series Circuit: Single path for current. Current is identical through all components. Voltages drop across each load (V_total = V1 + V2). Total resistance increases (R_total = R1 + R2).',
        'Parallel Circuit: Multiple paths for current. Voltage is identical across all branches. Currents split and add up (I_total = I1 + I2). Total equivalent resistance decreases (1/R_total = 1/R1 + 1/R2).',
      ],
      codeSnippet: 'Series Resistance: R_eq = R1 + R2 + R3\nParallel Resistance: R_eq = 1 / ( (1/R1) + (1/R2) + (1/R3) )',
    ),
    CheatsheetSection(
      title: 'Active Components: Diodes & Transistors',
      content: 'Semiconductor components permit active switching and direction control of electrical flow.',
      bulletPoints: [
        'Diode: Permits electrical current flow in one direction (Forward Biased) and blocks it in the reverse direction (Reverse Biased).',
        'LED (Light Emitting Diode): A diode that emits light when current passes forward through it.',
        'Transistor: Three-terminal semiconductor device used to amplify electrical signals or act as an electronic switch. The foundational building block of microprocessors and logic gates.',
      ],
      codeSnippet: 'Diode Anode (+): Connect to positive voltage\nDiode Cathode (-): Connect to negative/ground (marked with stripe)',
    ),
  ],
);
