import '../../models/flashcard.dart';

final List<Flashcard> linuxFlashcards = [
  Flashcard(
    frontTitle: 'What does chmod 755 mean?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'chmod 755',
    backExplanation: 'chmod uses octal notation where each digit represents Owner, Group, and Others permissions. 7=rwx (read+write+execute), 5=r-x (read+execute). So 755 = owner can do everything; group and others can read and execute.',
    bulletPoints: [
      'r=4, w=2, x=1. Add them together: rwx=7, rw-=6, r-x=5, r--=4.',
      'chmod 644: owner rw-, group r--, others r-- (typical for files).',
      'chmod 700: only owner has full access (private scripts/dirs).',
    ],
    codeSnippet: '# Common permission patterns:\nchmod 755 script.sh    # -rwxr-xr-x (executable script)\nchmod 644 index.html   # -rw-r--r-- (web file)\nchmod 600 ~/.ssh/id_rsa # -rw------- (SSH private key)\nchmod 700 ~/.ssh/       # drwx------ (SSH directory)\nchmod +x deploy.sh      # add execute bit (symbolic mode)',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is the difference between a process and a thread?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'Process vs. Thread',
    backExplanation: 'A process is an independent program instance with its own memory space, file descriptors, and PID. A thread is a unit of execution within a process — threads share the process\'s memory space and resources.',
    bulletPoints: [
      'Process creation: fork() (clone parent) then exec() (replace with new program).',
      'Threads: created with clone() in Linux (pthreads library at user level).',
      'IPC between processes: pipes, sockets, shared memory, signals.',
    ],
    codeSnippet: r'''# List processes with threads
ps -eLf                    # all threads
ls /proc/$(pgrep nginx)/task/  # thread dirs for nginx PID

# Process tree
pstree -p                  # show PIDs in tree
htop  # Press H to show/hide threads''',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What are Linux signals?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'Linux Signals',
    backExplanation: 'Signals are software interrupts sent to processes to notify them of events. Each signal has a default action (terminate, core dump, ignore, stop). Processes can handle most signals except SIGKILL and SIGSTOP.',
    bulletPoints: [
      'SIGTERM (15): graceful shutdown request — process should clean up and exit.',
      'SIGKILL (9): immediate forced termination — cannot be caught or ignored.',
      'SIGHUP (1): terminal hangup; convention to reload config (nginx, sshd).',
      'SIGINT (2): sent by Ctrl+C — interrupts foreground process.',
    ],
    codeSnippet: r'''# Send signals to processes
kill -15 1234         # SIGTERM: polite shutdown
kill -9 1234          # SIGKILL: force kill
kill -HUP $(pgrep nginx)  # reload nginx config

# List all signals
kill -l''',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is the Linux /proc filesystem?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: '/proc Virtual Filesystem',
    backExplanation: 'A pseudo-filesystem in Linux exposing kernel and process information as files. Not stored on disk — dynamically generated by the kernel. Provides a window into running system state.',
    bulletPoints: [
      '/proc/PID/: per-process directory with cmdline, status, fd, maps, etc.',
      '/proc/cpuinfo: CPU hardware details.',
      '/proc/meminfo: memory usage breakdown.',
      '/proc/sys/: kernel tuning parameters (readable and writable).',
    ],
    codeSnippet: r'''# Explore /proc
cat /proc/cpuinfo          # CPU details
cat /proc/meminfo          # memory stats
cat /proc/$$/status        # current shell process
ls -la /proc/$$/fd         # open file descriptors

# Tune kernel parameter at runtime
echo 1 > /proc/sys/net/ipv4/ip_forward''',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is systemd and how does it differ from init?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'systemd vs. init',
    backExplanation: 'systemd is the modern Linux init system (PID 1) and service manager, replacing legacy SysV init. It manages system services as "units" using declarative configuration files, enabling parallel startup, dependency tracking, and socket activation.',
    bulletPoints: [
      'SysV init: sequential startup via shell scripts in /etc/rc*.d/ — slow.',
      'systemd: parallel service startup using dependency graph — much faster boot.',
      'Unit types: .service, .socket, .timer, .mount, .target, .path.',
    ],
    codeSnippet: '# systemctl cheatsheet\nsystemctl start nginx      # start service\nsystemctl stop nginx       # stop service\nsystemctl enable nginx     # start at boot\nsystemctl status nginx     # show status and logs\njournalctl -u nginx -f     # follow service logs\nsystemctl list-units --type=service --state=running',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is the Linux boot process?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'Linux Boot Process',
    backExplanation: 'Linux boots through a defined sequence: BIOS/UEFI → Bootloader (GRUB) → Kernel loads and mounts initramfs → Kernel starts PID 1 (systemd) → systemd brings up services → Login prompt.',
    bulletPoints: [
      'BIOS/UEFI: POST, finds boot device, loads MBR or EFI partition.',
      'GRUB2: Loads kernel and initial RAM disk (initramfs) into memory.',
      'initramfs: Temporary root filesystem in RAM for early boot drivers (storage, encryption).',
      'systemd: Starts all configured services in parallel based on dependency graph.',
    ],
    codeSnippet: '# Boot time analysis\nsystemd-analyze          # total boot time\nsystemd-analyze blame    # per-service boot time\nsystemd-analyze plot > boot.svg  # visual timeline\n\n# Check kernel messages from boot\ndmesg | head -50\njournalctl -b            # all logs from current boot',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is cron and crontab syntax?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'cron & crontab',
    backExplanation: 'cron is the Linux daemon for scheduling recurring tasks. crontab defines the schedule using a 5-field time expression followed by the command to run.',
    bulletPoints: [
      'Fields: minute (0-59), hour (0-23), day-of-month (1-31), month (1-12), day-of-week (0-7).',
      '* = any value; */5 = every 5; 1,3,5 = at 1, 3, and 5.',
      'Special strings: @reboot, @hourly, @daily, @weekly, @monthly.',
    ],
    codeSnippet: '# Edit user crontab\ncrontab -e\n\n# crontab examples:\n# ┌── min  ┌── hour  ┌── dom  ┌── month  ┌── dow\n# │        │         │        │          │\n  0  2  *  *  0   /usr/local/bin/backup.sh  # every Sunday at 2am\n  */5 *  *  *  *   /opt/healthcheck.sh       # every 5 minutes\n  0   8  1  *  *   /opt/monthly-report.sh    # 1st of month at 8am',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is the difference between hard link and soft link?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'Hard Link vs. Soft (Symbolic) Link',
    backExplanation: 'A hard link is a directory entry pointing to the same inode (data blocks) as the original file. A symbolic (soft) link is a special file containing the path to the target — like a shortcut.',
    bulletPoints: [
      'Hard link: deleting original doesn\'t affect the link — same inode. Same filesystem only.',
      'Soft link: if original is deleted, link becomes broken ("dangling symlink"). Can cross filesystems.',
      'ln <src> <dest>: hard link; ln -s <src> <dest>: symbolic link.',
    ],
    codeSnippet: '# Hard link — same inode number\nln /etc/hosts /tmp/hosts-link\nls -li /etc/hosts /tmp/hosts-link  # same inode shown\n\n# Symbolic link\nln -s /var/log/nginx/access.log ./access.log\nls -la ./access.log  # shows -> target path\nreadlink -f ./access.log  # resolve full path',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is iptables?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'iptables',
    backExplanation: 'iptables is the traditional Linux firewall tool for configuring the kernel\'s Netfilter packet filtering framework. Rules are organized into tables (filter, nat, mangle) and chains (INPUT, OUTPUT, FORWARD, PREROUTING, POSTROUTING).',
    bulletPoints: [
      'filter table: main table for firewall rules (accept/drop/reject).',
      'nat table: network address translation (DNAT, SNAT, MASQUERADE).',
      'Rule evaluation: top-to-bottom, first match wins.',
      'nftables: modern replacement for iptables with better performance and syntax.',
    ],
    codeSnippet: '# Allow established connections and SSH, drop all else\niptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT\niptables -A INPUT -p tcp --dport 22 -j ACCEPT\niptables -A INPUT -p tcp --dport 80 -j ACCEPT\niptables -P INPUT DROP\n\n# List rules with line numbers\niptables -L INPUT --line-numbers -n -v',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is SSH and how does key-based auth work?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'SSH Key-Based Authentication',
    backExplanation: 'SSH (Secure Shell) uses asymmetric cryptography for key-based auth. The client presents its public key; the server verifies the client owns the corresponding private key via a cryptographic challenge — no password transmitted.',
    bulletPoints: [
      'Generate key pair with ssh-keygen. Private key stays local; public key goes to server.',
      '~/.ssh/authorized_keys on server: contains accepted public keys.',
      'ssh-agent: holds decrypted private keys in memory so you don\'t re-enter passphrase.',
    ],
    codeSnippet: '# Generate ED25519 key pair (modern, secure)\nssh-keygen -t ed25519 -C "user@laptop" -f ~/.ssh/id_ed25519\n\n# Copy public key to remote server\nssh-copy-id -i ~/.ssh/id_ed25519.pub user@server\n\n# Use specific key\nssh -i ~/.ssh/id_ed25519 user@server\n\n# SSH config for shortcuts (~/.ssh/config)\nHost prod\n  HostName 10.0.1.5\n  User ubuntu\n  IdentityFile ~/.ssh/id_ed25519',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is disk partitioning and LVM?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'Partitioning & LVM',
    backExplanation: 'Disk partitioning divides physical disks into isolated regions. LVM (Logical Volume Manager) adds an abstraction layer over physical disks, enabling flexible resizing, snapshots, and spanning multiple disks.',
    bulletPoints: [
      'Physical Volume (PV): a disk or partition initialized for LVM.',
      'Volume Group (VG): pool of storage combining one or more PVs.',
      'Logical Volume (LV): virtual partition carved from a VG — mounted as a filesystem.',
    ],
    codeSnippet: '# Create LVM setup\npvcreate /dev/sdb             # init physical volume\nvgcreate vg_data /dev/sdb     # create volume group\nlvcreate -L 50G -n lv_app vg_data  # create 50GB logical volume\nmkfs.ext4 /dev/vg_data/lv_app # format\nmount /dev/vg_data/lv_app /data\n\n# Extend logical volume online\nlvextend -L +20G /dev/vg_data/lv_app\nresize2fs /dev/vg_data/lv_app',
    isConcept: true,
  ),
  Flashcard(
    frontTitle: 'What is the Linux OOM Killer?',
    frontSubtitle: 'LINUX CONCEPT',
    backTitle: 'OOM Killer',
    backExplanation: 'When the Linux kernel cannot satisfy a memory allocation request, the Out-Of-Memory Killer selects a process to terminate to free memory. It scores each process based on memory usage, runtime, privilege, and oom_adj/oom_score_adj tunable.',
    bulletPoints: [
      'Triggered when physical RAM and swap are exhausted.',
      'oom_score_adj: set -1000 to protect a process; 1000 to make it first target.',
      'OOM kills appear in kernel logs: dmesg | grep -i "killed process".',
    ],
    codeSnippet: r'''# View OOM scores for running processes\nfor pid in /proc/[0-9]*/; do\n  printf "%5d %s\\n" \\\n    $(cat ${pid}oom_score 2>/dev/null) \\\n    $(cat ${pid}comm 2>/dev/null)\ndone | sort -rn | head -20\n\n# Protect critical process from OOM killer\necho -1000 > /proc/$(pgrep postgres)/oom_score_adj''',
    isConcept: true,
  ),
];


