package com.ac.motdujour;

import java.util.HashMap;
import java.util.Map;

public class WordsUtil {
    public static final Map<String, String> WORDS = new HashMap<>();

    static {
        WORDS.put("Amphigouri", "Nonsense or gibberish, especially in a piece of writing.");
        WORDS.put("Boustrophédon", "An ancient method of writing in which the lines run alternately from right to left and from left to right.");
        WORDS.put("Callipyge", "Having beautifully shaped buttocks.");
        WORDS.put("Dégueulasse", "Disgusting or revolting.");
        WORDS.put("Élucubration", "Excessively detailed and complicated thought or discussion.");
        WORDS.put("Farniente", "Idleness or leisure, often with a connotation of carefree laziness.");
        WORDS.put("Gourgandine", "A promiscuous woman.");
        WORDS.put("Hypnagogique", "Relating to the state immediately before falling asleep.");
        WORDS.put("Irréfragable", "Impossible to refute or disprove.");
        WORDS.put("Jocrisse", "A simpleton or a fool.");
        WORDS.put("Kermesse", "A fair or festival, typically one held outdoors.");
        WORDS.put("Lénifiant", "Soothing or calming.");
        WORDS.put("Mélioratif", "Having a positive or favorable connotation.");
        WORDS.put("Nébulosité", "Cloudiness or haziness.");
        WORDS.put("Obduré", "Stubbornly persistent in wrongdoing.");
        WORDS.put("Péripatéticien", "A wandering philosopher; often refers to a streetwalker in modern usage.");
        WORDS.put("Quidam", "An unknown or unnamed person.");
        WORDS.put("Ratiociner", "To reason or argue pointlessly or excessively.");
        WORDS.put("Sardanapalesque", "Excessively luxurious or extravagant.");
        WORDS.put("Truculent", "Fierce, cruel, or savagely brutal.");
        WORDS.put("Uchronie", "A hypothetical reconstruction of history, often to explore a different outcome.");
        WORDS.put("Vespéral", "Pertaining to the evening.");
        WORDS.put("Wagon-lit", "A sleeping car on a train.");
        WORDS.put("Xylophage", "An organism that eats wood.");
        WORDS.put("Ypérite", "Mustard gas (used in chemical warfare).");
        WORDS.put("Zinzolin", "A reddish-purple color.");
        WORDS.put("Aberration", "A departure from what is normal, usual, or expected, typically an unwelcome one.");
        WORDS.put("Balbutier", "To stutter or stammer.");
        WORDS.put("Cacographie", "Poor spelling or handwriting.");
        WORDS.put("Dépaysement", "The feeling of being in a foreign country or environment.");
        WORDS.put("Étinceler", "To sparkle or shine brightly.");
        WORDS.put("Facétieux", "Playful or humorous.");
        WORDS.put("Galimatias", "Nonsense or gibberish.");
        WORDS.put("Histrion", "An actor or performer.");
        WORDS.put("Iconoclaste", "A person who attacks or criticizes cherished beliefs or institutions.");
        WORDS.put("Jactance", "Boastfulness or bragging.");
        WORDS.put("Kakistocratie", "Government by the least qualified or most unprincipled citizens.");
        WORDS.put("Lassitude", "A state of physical or mental weariness; lack of energy.");
        WORDS.put("Muguet", "Lily of the valley (a fragrant flowering plant).");
        WORDS.put("Néophyte", "A person who is new to a subject, skill, or belief.");
        WORDS.put("Ostentatoire", "Characterized by vulgar or pretentious display; designed to impress or attract notice.");
        WORDS.put("Péremptoire", "Assertive or dictatorial.");
        WORDS.put("Quadrillage", "A pattern of squares or rectangles.");
        WORDS.put("Ratiocination", "The process of logical reasoning.");
        WORDS.put("Surréel", "Having qualities attributed to surrealism; dreamlike or bizarre.");
        WORDS.put("Téléologique", "Relating to the explanation of phenomena by the purpose they serve rather than by postulated causes.");
        WORDS.put("Ubiquité", "The state of being present, or seeming to be present, everywhere at once.");
        WORDS.put("Vagabondage", "The action or practice of wandering from place to place.");
        WORDS.put("Walachisme", "An irrational belief in the power of evil spirits or the supernatural.");
        WORDS.put("Xénophobie", "Dislike of or prejudice against people from other countries.");
        WORDS.put("Yodle", "To sing with frequent changes from the natural voice to falsetto.");
        WORDS.put("Zoologie", "The scientific study of the behavior, structure, physiology, and classification of animals.");
        WORDS.put("Avalanche", "A sudden arrival or occurrence of a large amount of something.");
        WORDS.put("Bricolage", "The construction or creation of something using a diverse range of materials or resources.");
        WORDS.put("Clandestin", "Kept secret or done secretively, especially because illicit.");
        WORDS.put("Déjà vu", "A feeling of having already experienced the present situation.");
        WORDS.put("Éclat", "Brilliance or impressive display.");
        WORDS.put("Fiasco", "A complete failure, typically in a humiliating or ludicrous way.");
        WORDS.put("Gourmet", "A connoisseur of good food; a person with a discerning palate.");
        WORDS.put("Haut cuisine", "High-quality cooking, especially as found in a gourmet restaurant.");
        WORDS.put("Innuendo", "An allusive or oblique remark or hint, typically a suggestive or disparaging one.");
        WORDS.put("Jubilant", "Feeling or expressing great happiness and triumph.");
        WORDS.put("Kitsch", "Art, objects, or design considered to be in poor taste because of excessive garishness or sentimentality, but sometimes appreciated in an ironic or knowing way.");
        WORDS.put("Liaison", "Communication or cooperation that facilitates a close working relationship between people or organizations.");
        WORDS.put("Malaise", "A general feeling of discomfort, illness, or unease whose exact cause is difficult to identify.");
        WORDS.put("Nostalgia", "A sentimental longing or wistful affection for the past, typically for a period or place with happy personal associations.");
        WORDS.put("Oblivion", "The state of being unaware or unconscious of what is happening.");
        WORDS.put("Pastiche", "An artistic work in a style that imitates that of another work, artist, or period.");
        WORDS.put("Quixotic", "Exceedingly idealistic; unrealistic and impractical.");
        WORDS.put("Rendezvous", "A meeting at an agreed time and place, typically between two people.");
        WORDS.put("Savoir-faire", "The ability to act or speak appropriately in social situations.");
        WORDS.put("Tête-à-tête", "A private conversation between two people.");
        WORDS.put("Ubiquitous", "Present, appearing, or found everywhere.");
        WORDS.put("Voracious", "Wanting or devouring great quantities of food.");
        WORDS.put("Wunderkind", "A person who achieves great success when relatively young.");
        WORDS.put("Xanadu", "An idealized place of great or idyllic magnificence and beauty.");
        WORDS.put("Yuletide", "The Christmas season.");
        WORDS.put("Zenith", "The highest point reached by a celestial or other object.");
    }
}
