import '../../models/cheatsheet.dart';

final Cheatsheet stockValuationCheatsheet = Cheatsheet(
  category: 'Stock Valuation',
  summary: 'Intrinsic valuation models, Discounted Cash Flow math, ratio analysis, and financial statement inspection.',
  sections: [
    CheatsheetSection(
      title: 'Discounted Cash Flow (DCF) Mechanics',
      content: 'DCF calculates the present value of all future cash flows expected to be generated by the business.',
      bulletPoints: [
        '1. Forecast Free Cash Flow (FCF) for 5-10 years.',
        '2. Calculate Terminal Value using perpetual growth model: TV = FCF_n * (1 + g) / (WACC - g).',
        '3. Discount cash flows to present day using WACC.',
        '4. Divide Total Equity Value by diluted share count to arrive at Intrinsic Value per share.',
      ],
      codeSnippet: '''
// DCF Valuation Formula
// PV = Sum( FCF_t / (1 + WACC)^t ) + TV / (1 + WACC)^n
''',
    ),
    CheatsheetSection(
      title: 'Key Valuation Ratios Reference',
      content: 'Multiples allow comparison of relative value across peers in the same sector.',
      bulletPoints: [
        'P/E (Price to Earnings): Market Price / Earnings Per Share.',
        'P/FCF (Price to Free Cash Flow): Market Cap / Annual Free Cash Flow (Best for profitability quality).',
        'EV/EBITDA: Enterprise Value / Operating Cash Earnings (Neutral to debt structure).',
        'Debt-to-Equity: Total Liabilities / Shareholders Equity (< 1.5 preferred).',
      ],
    ),
  ],
);
